### PR TITLE
fix: some windows versions don't make this directory?

### PR DESCRIPTION
**Pull request by nedbat**
This fixes the failing Windows tests, but I'm not sure if it's the right way. I don't know why those directories are missing on Windows 3.7 and 3.8.

### CODE REVIEW

**Comment by manueljacob** [comment]
In general, I don’t like to supress errors if I don’t understand why they happen. But is there any way to find out?

**Comment by nedbat** [comment]
I guess the way to find out is to get a Windows 3.7 or 3.8 installation and try those commands.  I'm not a fan of suppressing errors either, but in this case, we're trying to delete a directory.  Is it really an error that the directory doesn't exist in the first place?

**Comment by nedbat** [comment]
Another option is to check if the directory exists before trying to remove it.

**Comment by manueljacob** [comment]
I don’t think that checking that the directory exists has much advantage over suppressing the error.

The existence or non-existence of the directories is not at all relevant to the test. The reason why I added the code to delete the directories is to make it not blow up up in the cleanup part of `in_venv_world_fixture`, which deletes some files in the directory, but not directories. To be honest, I did not fully understand why it cleans up and why some directories are excluded from it (e.g. 1a6844ae32781f2117d46363ece697d509f6935d added another directory).

**Pull request closed without merging**
